# Filename: tide_extract_1site_harmonics.R
# Extract harmonics constituents for a single tide station to be used 
# elsewhere. The harmonics Rdata file needs to have been generated by the 
# tide_harmonics_parse.R script already. 
# Author: Luke Miller  May 3, 2012
###############################################################################

# Load the previously-generated harmonics file that contains data for all 666 
# sites around North America. 
load('Harmonics_20120302.Rdata')

# Specify a search string that will hopefully only return a single station
stationID = 'San Diego, San Diego Bay'
#stationID = 'Monterey Harbor'

# Find row index of the desired station in the harms list
stInd = grep(stationID, harms$station)

# We only want to hold on to starting constants for this year (and future years)
# so we'll get the year index for the current year so that we can dump data from
# earlier years
curr.date = as.POSIXlt(Sys.time())
curr.year = curr.date$year + 1900
year.ind = curr.year - harms$startyear + 1

# Specify number of years' worth of starting constants to keep
keep.years = 10

# Extract the useful bits from the harms list, keeping only data for the 
# desired tide station.
# NOAA generally reports 37 harmonic constituents for a tide station on their 
# site. These correspond to the first 37 constants listed in the XTide harmonics
# file, and all of the names match up except LDA2 (called LAM2 by NOAA). So we
# can just keep the first 37 constants instead of all 175 from the XTide file.
# These will give predictions that are well within the variance in tide height
# caused by local day-to-day weather conditions 
harms1 = list(name = harms$name[1:37], 
		speed = harms$speed[1:37],
		startyear = seq(curr.year, (curr.year+keep.years-1)),
		equilarg = harms$equilarg[1:37, year.ind:(year.ind+keep.years-1)],
		nodefactor = harms$nodefactor[1:37, year.ind:(year.ind+keep.years-1)],
		station = harms$station[stInd],
		units = harms$units[stInd],
		longitude = harms$longitude[stInd],
		latitude = harms$latitude[stInd],
		timezone = harms$timezone[stInd],
		tzfile = harms$tzfile[stInd],
		datum = harms$datum[stInd],
		A = harms$A[stInd,1:37],
		kappa = harms$kappa[stInd,1:37])

attr(harms1$equilarg, 'dimnames')[[1]] = harms1$name
attr(harms1$equilarg, 'dimnames')[[2]] = harms1$startyear
attr(harms1$nodefactor, 'dimnames')[[1]] = harms1$name
attr(harms1$nodefactor, 'dimnames')[[2]] = harms1$startyear



# The following lines are here to output the harmonic values in a format that 
# is easy to copy and paste into Arduino code. Just run the script, and copy the
# output on the command line to paste it into the Arduino .ino file. 

cat('// Selected station: ', harms1$station,'\n')
cat('const float Datum =', harms1$datum, '; // units in feet\n')
cat('// Harmonic constant names: ')
cat(harms1$name, sep = ', ')
cat('\n')
cat("// These names match the NOAA names, except LDA2 here is LAM2 on NOAA's site\n")
cat('const float Amp[] = {')
cat(harms1$A, sep = ',')
cat('};\n')
cat('const float Kappa[] = {')
cat(harms1$kappa, sep = ',')
cat('};\n')

cat('const float Speed[] = {')
cat(harms1$speed, sep = ',')
cat('};\n')

for (i in 1:ncol(harms1$equilarg)) {
	cat('const float Equilarg',harms1$startyear[i],'[] = {', sep = '')
	cat(harms1$equilarg[, i], sep = ',')
	cat('};\n')
}

for (i in 1:ncol(harms1$nodefactor)) {
	cat('const float Nodefactor',harms1$startyear[i],'[] = {', sep = '')
	cat(harms1$nodefactor[,i], sep = ',')
	cat('};\n')
}
