# Filename: tide_site_extract_harmonics.R
# Extract harmonics constituents for a single tide station to be used 
# elsewhere. The harmonics Rdata file needs to have been generated by the 
# tide_harmonics_parse.R script already. 

# Author: Luke Miller  June 8, 2012
###############################################################################

# Load the previously-generated harmonics file that contains data for all 637
# reference sites in North America. These are only for tide reference stations 
# maintained by NOAA. NOAA generates predictions for a few thousand other 
# 'subordinate' stations that are not included in this data set. The subordinate
# station predictions are generally made by applying a height offset 
# correction and high/low tide time correction to the predictions from the local
# reference station. If you wish to make predictions for one of these 
# subordinate stations you'll still need to first generate predictions for the 
# local reference station (contained in this data set) and apply your 
# corrections afterwards.
load('Harmonics_20120302.Rdata')

# Specify a search string that will hopefully only return a single station
#stationID = 'San Diego, San Diego Bay'
stationID = 'Monterey Harbor'
#stationID = 'San Francisco'
#stationID = 'Port San Luis'
# Find row index of the desired station in the harms list
stInd = grep(stationID, harms$station)

# We only want to hold on to starting constants for this year (and future years)
# so we'll get the year index for the current year so that we can dump data from
# earlier years
curr.date = as.POSIXlt(Sys.time())
curr.year = curr.date$year + 1900
year.ind = curr.year - harms$startyear + 1

# Specify number of years' worth of starting constants to keep
# More than 4 year's worth of constants starts to fill up the Arduino SRAM, and
# will not allow the program to run correctly.
keep.years = 10

# Extract the useful bits from the harms list, keeping only data for the 
# desired tide station.
# NOAA generally reports 37 harmonic constituents for a tide station on their 
# site. These correspond to the first 37 constants listed in the XTide harmonics
# file, and all of the names match up except LDA2 (called LAM2 by NOAA). So we
# can just keep the first 37 constants instead of all 175 from the XTide file.
# These will give predictions that are well within the variance in tide height
# caused by local day-to-day weather conditions. Note that the order of the 
# named constituents differs between the XTide harmonics file and the NOAA 
# web pages.
harms1 = list(name = harms$name[1:37], 
		speed = harms$speed[1:37],
		startyear = seq(curr.year, (curr.year+keep.years-1)),
		equilarg = harms$equilarg[1:37, year.ind:(year.ind+keep.years-1)],
		nodefactor = harms$nodefactor[1:37, year.ind:(year.ind+keep.years-1)],
		station = harms$station[stInd],
		units = harms$units[stInd],
		longitude = harms$longitude[stInd],
		latitude = harms$latitude[stInd],
		timezone = harms$timezone[stInd],
		tzfile = harms$tzfile[stInd],
		datum = harms$datum[stInd],
		A = harms$A[stInd,1:37],
		kappa = harms$kappa[stInd,1:37])

attr(harms1$equilarg, 'dimnames')[[1]] = harms1$name
attr(harms1$equilarg, 'dimnames')[[2]] = harms1$startyear
attr(harms1$nodefactor, 'dimnames')[[1]] = harms1$name
attr(harms1$nodefactor, 'dimnames')[[2]] = harms1$startyear
#########################################################
# Calculate starting values for subsequent years relative to unix epoch
yr.start = seq(curr.year, (curr.year + keep.years -1))
yr.unix = as.numeric(as.POSIXct(paste(yr.start,"1","1",sep = '-'))) - 
		as.numeric(as.POSIXct('1970-1-1'))

# Begin sending output to a text file for copying/pasting into the 
# Arduino sketch.
sink(file = 'Tides_Arduino_preamble.txt', type = 'output', split = TRUE,
		append = FALSE)

# The following lines output the harmonic values in a format that 
# is easy to copy and paste into Arduino code. Just run the script, and copy the
# output on the command line to paste it into the Arduino .ino file. 
cat('//-----------------------------------------------------\n')
cat('// Begin pasted section from R script "tide_site_extract_harmonics.R"\n')
cat('// Selected station: ', harms1$station,'\n')
cat("// The 'datum' printed here is the difference between mean sea level and \n") 
cat("// mean lower low water for the NOAA station. These two values can be \n") 
cat("// found for NOAA tide reference stations on the tidesandcurrents.noaa.gov\n")
cat("//  site under the datum page for each station.\n") 
cat('const float Datum =', harms1$datum, '; // units in feet\n')
cat('// Harmonic constant names: ')
cat(harms1$name, sep = ', ')
cat('\n')
cat("// These names match the NOAA names, except LDA2 here is LAM2 on NOAA's site\n")
cat("typedef float PROGMEM prog_float_t; // Need to define this type before use\n")
cat('PROGMEM prog_float_t Amp[] = {')
cat(harms1$A, sep = ',')
cat('};\n')
cat('PROGMEM prog_float_t Kappa[] = {')
cat(harms1$kappa, sep = ',')
cat('};\n')
cat("// Speed is unscaled, stored as the original float values\n")

cat('PROGMEM prog_float_t Speed[] = {')
cat(harms1$speed, sep = ',')
cat('};\n')

## Create code for a 4 year x 37 constituent array
cat('PROGMEM prog_float_t Equilarg[')
cat(keep.years)
cat('][37] = { \n')
for (i in 1:(ncol(harms1$equilarg)-1)) {
	cat('{')
	cat(harms1$equilarg[, i], sep = ',')
	cat('},\n')
}
cat('{')
cat(harms1$equilarg[ ,ncol(harms1$equilarg)], sep = ',')
cat('} \n };\n')
cat('\n')

cat('PROGMEM prog_float_t Nodefactor[')
cat(keep.years)
cat('][37] = { \n')
for (i in 1:(ncol(harms1$nodefactor)-1)) {
	cat('{')
	cat(harms1$nodefactor[, i], sep = ',')
	cat('},\n')
}
cat('{')
cat(harms1$nodefactor[ ,ncol(harms1$nodefactor)], sep = ',')
cat('} \n };\n')
cat('\n')

cat('// Define unix time values for the start of each year.\n')
cat('//                                      ')
cat(yr.start, sep = '       ')
cat('\n')
cat('PROGMEM prog_uint32_t startSecs[] = {')
cat(yr.unix, sep = ',')
cat('};\n\n')

cat('// 1st year of data in the Equilarg/Nodefactor/startSecs arrays.\n')
cat('const unsigned int startYear = ')
cat(yr.start[1], ';\n', sep = '')
cat('//------------------------------------------------------------------\n')
# Close the output text file
sink()